---

- name: clone project repo from git
  git:
    dest: "{{ local_neuralnet_dir }}"
    repo: "{{ neuralnet_git_repo_url }}"
    force: yes
    accept_hostkey: yes

# TODO: Find out when to do this, and do it only then
- name: get path to pip
  command: which pip
  register: pip_location
  failed_when: "{{ not pip_location }}"

- name: debug path to pip
  debug:
    msg: "Trying pip executable at {{ pip_location }}"

- name: pip install listed requirements

  vars:
  pip:
    requirements: "{{ local_neuralnet_dir }}requirements.txt"
    executable: "{{ pip_location.stdout_lines | first }}"
    extra_args: "--no-cache-dir" # allow large packages to install on small disks

- name: start application
  command: "python {{ local_neuralnet_dir }}sample.py"
  # command: "python {{ local_neuralnet_dir }}sample.py --data_dir {{local_neuralnet_dir}}data/rock \
  # --experiment_dir {{local_neuralnet_dir}}folk --save_dir {{local_neuralnet_dir}}verify"